Sys.setlocale("LC_TIME", "C")
datos <- read.csv("household_power_consumption.txt",sep=";", na.strings="?")
fecha1 <- as.Date("2007/02/01")
fecha2 <- as.Date("2007/02/02")
elige <- (as.Date(datos[,1],format="%d/%m/%Y")==fecha1 | as.Date(datos[,1],format="%d/%m/%Y")==fecha2)
datosdosdias <- datos[elige,]
fechas <- as.Date(datosdosdias[,1],format="%d/%m/%Y")
horas <- datosdosdias[,2]
fecha_hora <- paste(fechas,horas)
tiempo <- strptime(fecha_hora,"%Y-%m-%d %H:%M:%S")
png("plot4.png")
par(mfcol=c(2,2),mar=c(4,4,2,1))
plot(tiempo,datosdosdias[,3],type='l',xlab="",ylab="Global Active Power (kilowats)")
plot(tiempo,datosdosdias[,7],type='l',xlab="",ylab = "Energy sub metering")
points(tiempo,datosdosdias[,8],type="l",col="red")
points(tiempo,datosdosdias[,9],type="l",col="blue")
legend("topright",legend=c("Sub Metering 1","Sub Metering 2","Sub Metering 3"),lty=1,col=c("black","red","blue"))
plot(tiempo,datosdosdias[,5],type="l",xlab="datetime",ylab="Volatage")
plot(tiempo,datosdosdias[,4],type="l",xlab="datetime",ylab="Gloabal_reactive_power")
dev.off()